# Generated by Django 6.0.4 on 2026-05-01 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0003_alter_school_options_alter_schoolproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_received', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Received'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('expected_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('school_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_orders', to='schools.schoolproduct')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RESTOCK', 'Restock (Stock IN)'), ('SALE', 'Sale (Stock OUT)'), ('RETURN', 'Return'), ('EXCHANGE_IN', 'Exchange — Item Returned'), ('EXCHANGE_OUT', 'Exchange — New Item Given')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='schools.schoolproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
