# Generated by Django 6.0.4 on 2026-05-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='is_void',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('RESTOCK', 'Stock Added'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('EXCHANGE_IN', 'Exchange — Returned'), ('EXCHANGE_OUT', 'Exchange — Given')], max_length=20),
        ),
    ]
