# Generated by Django 6.0.4 on 2026-05-01 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_schoolproduct_sku_code'),
        ('transactions', '0002_stocktransaction_is_void_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('RESTOCK', 'Stock Added'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('EXCHANGE_IN', 'Exchange — Returned'), ('EXCHANGE_OUT', 'Exchange — Given'), ('BILL_SALE', 'Bill Sale')], max_length=20),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_void', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('size_value', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.bill')),
                ('school_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schoolproduct')),
            ],
        ),
    ]
