# Generated by Django 5.2.14 on 2026-05-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_stocktransaction_transaction_type_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('RESTOCK', 'Stock Added'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('EXCHANGE_IN', 'Exchange — Returned'), ('EXCHANGE_OUT', 'Exchange — Given'), ('BILL_SALE', 'Bill Sale'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=20),
        ),
    ]
