# Generated by Django 5.2.14 on 2026-05-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_schoolproduct_unique_together_and_more'),
        ('transactions', '0004_alter_stocktransaction_transaction_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='billitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='billitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='billitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='billitem_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='billitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='billitem_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_ordered__gt', 0)), name='mfg_quantity_ordered_positive'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gte', 0)), name='mfg_quantity_received_non_negative'),
        ),
    ]
