# Generated by Django 6.0.4 on 2026-05-01 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name'),
        ('schools', '0002_alter_school_code_alter_school_name_schoolproduct'),
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='schoolproduct',
            options={'ordering': ['school__name', 'product__name', 'size__size_value']},
        ),
        migrations.AddField(
            model_name='schoolproduct',
            name='low_stock_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='schoolproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='schoolproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_products', to='products.product'),
        ),
        migrations.AlterField(
            model_name='schoolproduct',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_products', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='schoolproduct',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_products', to='sizes.size'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolproduct',
            unique_together={('school', 'product', 'size')},
        ),
    ]
