# Generated by Django 6.0.4 on 2026-05-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name'),
        ('schools', '0003_alter_school_options_alter_schoolproduct_options_and_more'),
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolproduct',
            name='stock',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='schoolproduct',
            index=models.Index(fields=['school', 'product', 'size'], name='idx_school_product_size'),
        ),
        migrations.AddIndex(
            model_name='schoolproduct',
            index=models.Index(fields=['school', 'product'], name='idx_school_product'),
        ),
        migrations.AddIndex(
            model_name='schoolproduct',
            index=models.Index(fields=['stock'], name='idx_stock_level'),
        ),
    ]
