# Generated by Django 6.0.4 on 2026-05-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_schoolproduct_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolproduct',
            name='sku_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
    ]
