# Generated by Django 6.0.4 on 2026-05-02 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_schoolproduct_sku_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolproduct',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_products', to='schools.school'),
        ),
    ]
