# Generated by Django 5.2.14 on 2026-05-16 21:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name'),
        ('schools', '0006_alter_schoolproduct_school'),
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolproduct',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='uniq_school_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='schoolproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', False)), fields=('school', 'product', 'size'), name='uniq_school_product_size_specific'),
        ),
        migrations.AddConstraint(
            model_name='schoolproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', True)), fields=('product', 'size'), name='uniq_school_product_size_general'),
        ),
        migrations.AddConstraint(
            model_name='schoolproduct',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='schoolproduct_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='schoolproduct',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='schoolproduct_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='schoolproduct',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold__gte', 0)), name='schoolproduct_threshold_non_negative'),
        ),
    ]
