# Generated by Django 5.2.14 on 2026-05-16 21:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name'),
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='size',
            constraint=models.UniqueConstraint(models.F('product'), django.db.models.functions.text.Lower('size_value'), name='uniq_size_per_product_ci'),
        ),
    ]
